version: '3'

volumes:
  db-data:

services:
  db:
    image: postgres:12
    platform: linux/amd64
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db-data:/var/lib/postgres/data

  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    platform: linux/amd64
    ports:
      - "3000:3000"
    volumes:
      - .:/rails-docker
    environment:
      - POSTGRES_PASSWORD=postgres
    tty: true
    stdin_open: true
    depends_on:
      - db
    links:
      - db